var cardData = [
    {
        id: 1,
        image: "https://finanzvergleich.com/wp-content/uploads/2018/05/Gebuehrenfrei-Mastercard-Advanzia-140x88.png",
        rating: "1,1",
        feature: ["Gold-Karte mit Versicherungspaket", "Flexible Rückzahlung", "Einfache Beantragung"],
        Kartenanbieter: "gebührenfrei.de",
        Kartenname: "Gebührenfrei Mastercard Gold",
        Kartengesellschaft: "Mastercard",
        KartenArt: "Credit",
        Rechnungsausgleich: "Überweisung, flexible Rückzahlung",
        KartengebührProJahr: "0 €",
        EffJahreszins: "24,69 %",
        GirokontoBeiAnbieterNötig: "Nein",
        Partnerkarte: "Nein",
        KontaktlosBezahlen: "Ja",
        MobilBezahlen: ["Apple Pay", "Google Pay"],
        HaftungBeiKartenverlust: "50 €",
        Ersatzkarte: "0 €",
        KarteneinsatzInland: "0,00 %",
        KarteneinsatzEuroZone: "0,00 %",
        KarteneinsatzImAusland: "0,00 %",
        BargeldAbhebenInland: "0 %",
        BargeldAbhebenEuroZone: "0 %",
        BargeldAbhebenAusland: "0 %",
        Auslandskrankenversicherung: false,
        Reiseunfallversicherung: true,
        Reiserücktrittsversicherung: true,
        Reisegepäckversicherung: true,
        RechtsschutzFürMietwagen: false,
        HaftpflichtFürMietwagen: false,
        VollkaskoversicherungFürMietwagen: false,
        GeldZurückBonus: false,
        BonusPunktesystem: false,
        Startguthaben: false,
        Tankrabatt: false,
        RabatteAufMietwagen: true,
        Reiserabatte: true,
        Hotelrabatte: false,
        Gebühren: "8/11",
        Funktionen: "3/4",
        ZusatzLeistungen: "5/10",
        Beantragung: "13/15",
        Gesamt: "29/40",
        ZumAngebotLink: "https://sign-up.finanzvergleich.com/advanzia/advanzia-gold"
    }
    ,
    {
        id: 2,
        image: "https://finanzvergleich.com/wp-content/uploads/2023/02/bank_norwegian_credit_card_250px-002-140x88.png",
        rating: "1,1",
        feature: ["Zinsfrei in den ersten 45 Tagen", "Weltweit kostenlos bezahlen & abheben", "Kreditlimit bis 10.000 €"],
        Kartenanbieter: "Bank Norwegian",
        Kartenname: "Kreditkarte",
        Kartengesellschaft: "VISA",
        KartenArt: "Credit",
        Rechnungsausgleich: "Flexible Rückzahlung per Überweisung oder Lastschrift",
        KartengebührProJahr: "0 €",
        EffJahreszins: "24,40 %",
        GirokontoBeiAnbieterNötig: "Nein",
        Partnerkarte: "Nein",
        KontaktlosBezahlen: "Ja",
        MobilBezahlen: ["Apple Pay", "Google Pay", "Garmin Pay", "Fitbit Pay"],
        HaftungBeiKartenverlust: "50 €",
        Ersatzkarte: "0 €",
        KarteneinsatzInland: "0,00 %",
        KarteneinsatzEuroZone: "0,00 %",
        KarteneinsatzImAusland: "0,00 %",
        BargeldAbhebenInland: "0 %",
        BargeldAbhebenEuroZone: "0 %",
        BargeldAbhebenAusland: "0 %",
        Auslandskrankenversicherung: true,
        Reiseunfallversicherung: true,
        Reiserücktrittsversicherung: true,
        Reisegepäckversicherung: true,
        RechtsschutzFürMietwagen: false,
        HaftpflichtFürMietwagen: false,
        VollkaskoversicherungFürMietwagen: false,
        GeldZurückBonus: false,
        BonusPunktesystem: false,
        Startguthaben: false,
        Tankrabatt: false,
        RabatteAufMietwagen: false,
        Reiserabatte: false,
        Hotelrabatte: false,
        Gebühren: "11/11",
        Funktionen: "3/4",
        ZusatzLeistungen: "4/10",
        Beantragung: "10/15",
        Gesamt: "29/40",
        ZumAngebotLink: "https://www.banknorwegian.de/kreditkarte/?utm_source=financeads&utm_medium=cpa&utm_campaign=credit_card&utm_content=financeads&pid=fa-26398&anid=1440924212X26398C438298172TSd3f1f72580281cee"
    },
    {
        id: 3,
        image: "https://finanzvergleich.com/wp-content/uploads/2022/08/TF-Mastercard-Gold-140x90.png",
        rating: "1,2",
        feature: ["Individuelles Kreditkartenlimit", "Paket aus 4 Reiseversicherungen", "Flexible Ratenzahlungen möglich"],
        Kartenanbieter: "TF Bank",
        Kartenname: "TF Mastercard Gold",
        Kartengesellschaft: "Mastercard",
        KartenArt: "Credit",
        Rechnungsausgleich: "Überweisung, flexible Rückzahlung",
        KartengebührProJahr: "0 €",
        EffJahreszins: "24,79 %",
        GirokontoBeiAnbieterNötig: "Nein",
        Partnerkarte: "Nein",
        KontaktlosBezahlen: "Ja",
        MobilBezahlen: ["Apple Pay", "Google Pay"],
        HaftungBeiKartenverlust: "50 €",
        Ersatzkarte: "0 €",
        KarteneinsatzInland: "0,00 %",
        KarteneinsatzEuroZone: "0,00 %",
        KarteneinsatzImAusland: "0,00 %",
        BargeldAbhebenInland: "0 %",
        BargeldAbhebenEuroZone: "0 %",
        BargeldAbhebenAusland: "0 %",
        Auslandskrankenversicherung: true,
        Reiseunfallversicherung: true,
        Reiserücktrittsversicherung: true,
        Reisegepäckversicherung: true,
        RechtsschutzFürMietwagen: false,
        HaftpflichtFürMietwagen: false,
        VollkaskoversicherungFürMietwagen: false,
        GeldZurückBonus: true,
        BonusPunktesystem: false,
        Startguthaben: false,
        Tankrabatt: false,
        RabatteAufMietwagen: true,
        Reiserabatte: true,
        Hotelrabatte: false,
        Gebühren: "8/11",
        Funktionen: "3/4",
        ZusatzLeistungen: "7/10",
        Beantragung: "13/15",
        Gesamt: "28/40",
        ZumAngebotLink: "https://finanzvergleich.com/kreditkarte/tf-gold/?subid=d3f1f72580281cee&add_info=d3f1f72580281cee"
    },
    {
        id: 4,
        image: "https://finanzvergleich.com/wp-content/uploads/2023/09/image-20230911-115446-140x90.png",
        rating: "1,4",
        feature: ["Sofortauszahlung bis 2.000 €", "Flexible Rückzahlung", "Bäume pflanzen mit jedem echten Umsatz"],
        Kartenanbieter: "Hanseatic Bank GmbH & Co KG",
        Kartenname: "awa7® Visa Kreditkarte",
        Kartengesellschaft: "VISA",
        KartenArt: "Credit, Charge",
        Rechnungsausgleich: "Überweisung, flexible Rückzahlung",
        KartengebührProJahr: "0 €",
        EffJahreszins: "22,08 %",
        GirokontoBeiAnbieterNötig: "Nein",
        Partnerkarte: "Nein",
        KontaktlosBezahlen: "Ja",
        MobilBezahlen: ["Apple Pay", "Google Pay"],
        HaftungBeiKartenverlust: "50 €",
        Ersatzkarte: "9 €",
        KarteneinsatzInland: "0,00 %",
        KarteneinsatzEuroZone: "0,00 %",
        KarteneinsatzImAusland: "0,00 %",
        BargeldAbhebenInland: "0 %",
        BargeldAbhebenEuroZone: "0 %",
        BargeldAbhebenAusland: "0 %",
        Auslandskrankenversicherung: false,
        Reiseunfallversicherung: false,
        Reiserücktrittsversicherung: false,
        Reisegepäckversicherung: false,
        RechtsschutzFürMietwagen: false,
        HaftpflichtFürMietwagen: false,
        VollkaskoversicherungFürMietwagen: false,
        GeldZurückBonus: true,
        BonusPunktesystem: false,
        Startguthaben: false,
        Tankrabatt: false,
        RabatteAufMietwagen: false,
        Reiserabatte: true,
        Hotelrabatte: false,
        Gebühren: "11/11",
        Funktionen: "4/4",
        ZusatzLeistungen: "2/10",
        Beantragung: "9/15",
        Gesamt: "26/40",
        ZumAngebotLink: "https://awa7.de/antrag-fq-lp?ids=FINQlp23B1&fsid=65b4fa57c13aacb37f8b463d"
    },
    {
        id: 5,
        image: "https://finanzvergleich.com/wp-content/uploads/2023/08/Extrakarte_250px-140x88.png",
        rating: "1,7",
        feature: ["Ohne Jahresgebühr", "Flexible Rückzahlung", "Hohe Annahmequote"],
        Kartenanbieter: "Novum Bank Limited",
        Kartenname: "Extra Karte Mastercard",
        Kartengesellschaft: "Mastercard",
        KartenArt: "Credit",
        Rechnungsausgleich: "Überweisung, flexible Rückzahlung",
        KartengebührProJahr: "0 €",
        EffJahreszins: "24,60 %",
        GirokontoBeiAnbieterNötig: "Nein",
        Partnerkarte: "Nein",
        KontaktlosBezahlen: "Ja",
        MobilBezahlen: ["Apple Pay", "Google Pay"],
        HaftungBeiKartenverlust: "50 €",
        Ersatzkarte: "15 €",
        KarteneinsatzInland: "0,00 %",
        KarteneinsatzEuroZone: "0,00 %",
        KarteneinsatzImAusland: "2,99 %",
        BargeldAbhebenInland: "3,00 %, mind. 3,00 €",
        BargeldAbhebenEuroZone: "3,00 %, mind. 3,00 €",
        BargeldAbhebenAusland: "3,00 %, mind. 3,00 € + 2,99 %",
        Auslandskrankenversicherung: false,
        Reiseunfallversicherung: false,
        Reiserücktrittsversicherung: false,
        Reisegepäckversicherung: false,
        RechtsschutzFürMietwagen: false,
        HaftpflichtFürMietwagen: false,
        VollkaskoversicherungFürMietwagen: false,
        GeldZurückBonus: false,
        BonusPunktesystem: false,
        Startguthaben: false,
        Tankrabatt: false,
        RabatteAufMietwagen: false,
        Reiserabatte: false,
        Hotelrabatte: false,
        Gebühren: "8/11",
        Funktionen: "2/4",
        ZusatzLeistungen: "0/10",
        Beantragung: "13/15",
        Gesamt: "23/40",
        ZumAngebotLink: ""
    }
];

export default cardData;